# Generated by Django 5.2.4 on 2025-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_year',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
