# Generated by Django 5.2.4 on 2025-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_login_id_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
